# rosindustrial/viz:kinetic
FROM rosindustrial/webtools:kinetic
LABEL maintainer "Austin.Deric@gmail.com"
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN mkdir -p /workspace/src
COPY launch_maker.py /
ENTRYPOINT []
CMD []

